// Generated by CoffeeScript 1.6.2
var collections, connected, mongoClient, mongoServer, s,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

collections = (s = Meteor.settings) && s["public"] ? s["public"].mongo : {};

connected = [];

mongoServer = function(mongo) {
  return x.keys(mongo).filter(function(c) {
    return __indexOf.call(connected, c) < 0;
  }).map(function(k) {
    connected.push(k);
    db[k] = new Meteor.Collection(k);
    db[k].allow(x.func(mongo[k].allow, mongo[k]) || {
      insert: function(doc) {
        return true;
      },
      update: function(userId, doc, fields, modifier) {
        return false;
      },
      remove: function(userId, doc) {
        return false;
      }
    });
    db[k].deny(x.func(mongo[k].deny, mongo[k]) || {
      remove: function(userId, doc) {
        return true;
      }
    });
    return Meteor.publish(k, mongo[k].publish || function() {
      return db[k].find({});
    });
  });
};

mongoClient = function(mongo) {
  return x.keys(mongo).filter(function(c) {
    return __indexOf.call(connected, c) < 0;
  }).map(function(k) {
    connected.push(k);
    db[k] = new Meteor.Collection(k);
    return Meteor.subscribe(k);
  });
};

Meteor.startup(function() {
  var Modules;

  Modules = x.func(exports.Modules);
  x.keys(exports).filter(function(k) {
    var _ref;

    return ('a' <= (_ref = k[0]) && _ref <= 'z');
  }).map(function(file) {
    return x.extend(Modules, x.func(exports[file].Modules));
  });
  x.keys(this.Modules = Modules).map(function(n) {
    return x.module.call(this, n, Modules[n]);
  });
  if (Meteor.isServer) {
    x.isEmpty(collections) || mongoServer(collections);
    return x.keys(Modules).map(function(name) {
      var _;

      _ = x.func(Modules[name], x.func(Modules[name]));
      _.methods && Meteor.methods(_.methods);
      _.mongo && mongoServer(_.mongo);
      return _.onServerStartup && _.onServerStartup.call(_);
    });
  } else if (Meteor.isClient) {
    x.isEmpty(collections) || mongoClient(collections);
    Router.configure({
      layoutTemplate: 'layout'
    });
    x.keys(Modules).map(function(name) {
      var _;

      _ = x.func(Modules[name], x.func(Modules[name]));
      _.mongo && mongoClient(_.mongo);
      _.onStartup && _.onStartup.call(_);
      _.router && console.log('O') || Router.map(function() {
        return this.route(name, x.extend(_.router));
      });
      _.events && Template[name].events(x.tideEventKey(x.func(_.events, _), _.id));
      _.helpers && Template[name].helpers(x.func(_.helpers, _));
      _.on$Ready && $(function($) {
        return _.on$Ready.call(_);
      });
      return ('onCreated onRendered onDestroyed'.split(' ')).forEach(function(d) {
        return _[d] && Template[name][d](function() {
          return _[d].call(_);
        });
      });
    });
    return $(function($) {
      var k, _results;

      o.$.map(function(f) {
        return f();
      });
      _results = [];
      for (k in x.$) {
        _results.push($.fn[k] = x.$[k]);
      }
      return _results;
    });
  }
});
