// Generated by CoffeeScript 1.6.2
var collections, connected, dbClient, dbServer, s,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

collections = (s = Meteor.settings) && s["public"] ? x.toArray(s["public"].collections) : [];

connected = [];

dbServer = function(c) {
  return c.filter(function(c) {
    var _ref;

    return _ref = !c, __indexOf.call(connected, _ref) >= 0;
  }).map(function(collection) {
    connected.push(collection);
    db[collection] = new Meteor.Collection(collection);
    db[collection].allow({
      insert: function(doc) {
        return true;
      },
      update: function(userId, doc, fields, modifier) {
        return true;
      },
      remove: function(userId, doc) {
        return true;
      }
    });
    db[collection].deny({
      update: function(userId, doc, fields, modifier) {
        return false;
      },
      remove: function(userId, doc) {
        return false;
      }
    });
    return Meteor.publish(collection, function() {
      return db[collection].find({});
    });
  });
};

dbClient = function(c) {
  return c.filter(function(c) {
    var _ref;

    return _ref = !c, __indexOf.call(connected, _ref) >= 0;
  }).map(function(collection) {
    connected.push(collection);
    db[collection] = new Meteor.Collection(collection);
    return Meteor.subscribe(collection);
  });
};

Meteor.startup(function() {
  var Modules;

  Modules = x.func(exports.Modules);
  x.keys(exports).filter(function(k) {
    var _ref;

    return ('a' <= (_ref = k[0]) && _ref <= 'z');
  }).map(function(file) {
    return x.extend(Modules, x.func(exports[file].Modules));
  });
  x.keys(this.Modules = Modules).map(function(n) {
    return x.module.call(this, n, Modules[n]);
  });
  if (Meteor.isServer) {
    collections.length && dbServer(collections);
    return x.keys(Modules).map(function(name) {
      var _;

      _ = x.func(Modules[name], x.func(Modules[name]));
      _.methods && Meteor.methods(_.methods);
      _.collections && dbServer(x.toArray(_.collections));
      return _.onServerStartup && _.onServerStartup.call(_);
    });
  } else if (Meteor.isClient) {
    collections.length && dbClient(collections);
    Router.configure({
      layoutTemplate: 'layout'
    });
    x.keys(Modules).map(function(name) {
      var _;

      _ = x.func(Modules[name], x.func(Modules[name]));
      _.collections && dbClient(x.toArray(_.collections));
      _.onStartup && _.onStartup.call(_);
      _.router && console.log('O') || Router.map(function() {
        return this.route(name, x.extend(_.router));
      });
      _.events && Template[name].events(x.tideEventKey(x.func(_.events, _), _.id));
      _.helpers && Template[name].helpers(x.func(_.helpers, _));
      _.on$Ready && $(function($) {
        return _.on$Ready.call(_);
      });
      return ('onCreated onRendered onDestroyed'.split(' ')).forEach(function(d) {
        return _[d] && Template[name][d](function() {
          return _[d].call(_);
        });
      });
    });
    return $(function($) {
      var k, _results;

      o.$.map(function(f) {
        return f();
      });
      _results = [];
      for (k in x.$) {
        _results.push($.fn[k] = x.$[k]);
      }
      return _results;
    });
  }
});
