// Generated by CoffeeScript 1.6.2
var ElementNames, addAttribute, attributeClass, attributes;

ElementNames = 'a abbr acronym address applet area article aside audio b base basefont bdi bdo big blockquote body br button canvas caption center cite code col colgroup command data datagrid datalist dd del details dfn dir div dl dt em embed eventsource fieldset figcaption figure font footer form frame frameset h1 h2 h3 h4 h5 h6 head header hgroup hr html i iframe img input ins isindex kbd keygen label legend li link main map mark menu meta meter nav noframes noscript object ol optgroup option output p param pre progress q rp rt ruby s samp script section select small source span strike strong style sub summary sup table tbody td textarea tfoot th thead time title tr track tt u ul var video wbr'.toUpperCase().split(' ');

attributeClass = function(key, value) {
  if (value) {
    return value.replace(/\*/g, x.key2class(key));
  } else {
    return x.key2class(key);
  }
};

addAttribute = function(o, attr, value, seperator) {
  if (seperator == null) {
    seperator = ' ';
  }
  return x.object(o, attr, o[attr] && o[attr].length > 0 ? o[attr] + seperator + value : value);
};

attributes = function(obj) {
  return x.reduceKeys(obj, {}, function(o, k) {
    switch (false) {
      case !x.check('class', k):
        return addAttribute(o, 'class', attributeClass(k, x.parseValue(obj[k])));
      case k !== 'class':
        return addAttribute(o, 'class', x.parseValue(obj[k]));
      default:
        return x.object(o, x.dasherize(k), x.parseValue(obj[k]));
    }
  });
};

if (Meteor.isClient) {
  ElementNames.forEach(function(a) {
    return window[a] = function(obj, str) {
      obj = attributes(obj);
      if (str) {
        return HTML.toHTML(HTML[a](obj, str));
      } else {
        return HTML.toHTML(HTML[a](obj));
      }
    };
  });
}
